Repository leehe228/mungkive-app, pull requests merged in 2025-05, with the labels that each got.

#6 [Design] #5 - Welcome 및 Login 화면 UI 구현
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/java/com/mungkive/application/uicomponents/LoginView.kt
  app/src/main/java/com/mungkive/application/uicomponents/WelcomeView.kt
  app/src/main/res/drawable/dummylogo.png
Labels: Design

#13 [FEAT] #11: Navigation 추가 및 화면 연결 구성 완료
  app/build.gradle.kts
  app/src/main/java/com/mungkive/application/MainActivity.kt
  app/src/main/java/com/mungkive/application/model/BarItem.kt
  app/src/main/java/com/mungkive/application/model/NavBarItems.kt
  app/src/main/java/com/mungkive/application/model/Routes.kt
  app/src/main/java/com/mungkive/application/navigation/AppNavHost.kt
  app/src/main/java/com/mungkive/application/navigation/AuthNavGraph.kt
  app/src/main/java/com/mungkive/application/navigation/BottomNavigationBar.kt
  app/src/main/java/com/mungkive/application/navigation/MainNavGraph.kt
  app/src/main/java/com/mungkive/application/ui/MainApp.kt
  app/src/main/java/com/mungkive/application/ui/MainScreen.kt
  app/src/main/java/com/mungkive/application/ui/feed/FeedListView.kt
  app/src/main/java/com/mungkive/application/ui/main/MainScaffold.kt
  app/src/main/java/com/mungkive/application/ui/map/MapView.kt
  app/src/main/java/com/mungkive/application/ui/profile/ProfileView.kt
  app/src/main/java/com/mungkive/application/ui/tip/TipListView.kt
  app/src/main/res/drawable/ic_feed.xml
  app/src/main/res/drawable/ic_feed_on.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_map_on.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_profile_on.xml
  app/src/main/res/drawable/ic_tip.xml
  app/src/main/res/drawable/ic_tip_on.xml
  gradle/libs.versions.toml
Labels: Feat

#9 [Design] #7 - Profile 등록 및 수정 화면 UI 구현
  app/src/main/java/com/mungkive/application/models/ProfileViewStatus.kt
  app/src/main/java/com/mungkive/application/uicomponents/ProfileView.kt
  app/src/main/res/drawable/dummyprofile.png
Labels: Design

#20 [Design] #19 - Tip 화면 UI 구현
  app/src/main/java/com/mungkive/application/models/tip/TipData.kt
  app/src/main/java/com/mungkive/application/models/tip/TipDataFactory.kt
  app/src/main/java/com/mungkive/application/ui/tip/TipListView.kt
  app/src/main/java/com/mungkive/application/ui/tip/TipView.kt
  app/src/main/res/drawable/tip1.png
  app/src/main/res/drawable/tip2.png
  app/src/main/res/drawable/tip3.png
Labels: Design

#22 [Chore] #21 - ProfileView 중복 파일 제거 및 위치 이동
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/mungkive/application/ui/login/ProfileView.kt
  app/src/main/java/com/mungkive/application/ui/profile/ProfileView.kt
Labels: Chore

#30 [Chore] #29 - MapView 코드 수정
  app/src/main/java/com/mungkive/application/ui/map/MapView.kt
Labels: Chore

#35 [Design] #34 - RegisterView 화면 UI 구현
  app/src/main/java/com/mungkive/application/ui/register/RegisterView.kt
Labels: Design

#40 [Feat] #33 - 반려동물 프로필 ViewModel 구현
  app/src/main/java/com/mungkive/application/models/profile/ProfileData.kt
  app/src/main/java/com/mungkive/application/ui/profile/ProfileView.kt
  app/src/main/java/com/mungkive/application/viewmodels/ProfileViewModel.kt
Labels: Feat

#43 [Feat] #39 - 서버 통신 Manager 모듈 개발
  app/build.gradle.kts
  app/src/main/java/com/mungkive/application/MainActivity.kt
  app/src/main/java/com/mungkive/application/core/TokenManager.kt
  app/src/main/java/com/mungkive/application/network/ApiService.kt
  app/src/main/java/com/mungkive/application/network/AuthInterceptor.kt
  app/src/main/java/com/mungkive/application/network/AuthService.kt
  app/src/main/java/com/mungkive/application/network/NetworkModule.kt
  app/src/main/java/com/mungkive/application/network/dto/Models.kt
  app/src/main/java/com/mungkive/application/ui/test/ApiTestScreen.kt
  app/src/main/java/com/mungkive/application/viewmodels/ApiTestViewModel.kt
  gradle/libs.versions.toml
Labels: Feat
